//! Markdown and YAML artifacts.
//!
//! Write-through: every DB mutation regenerates the `## Plan index` and
//! `## Done` sections of `plans.md` plus `plans.yaml`. The rest of the file
//! stays untouched.

use std::fmt::Write as _;

use anyhow::Context;

use crate::db::{self, Plan};
use crate::state::Project;

// ---------- plans.md ----------

fn render_index(plans: &[Plan], deps: &[(String, String)]) -> String {
    let mut out = String::from("## Plan index\n\n");
    out.push_str("| Name | Status | Order | Depends on | Goal |\n|---|---|---|---|---|\n");
    for p in plans {
        let dep_list: Vec<String> = deps
            .iter()
            .filter(|(a, _)| a == &p.name)
            .map(|(_, b)| format!("`{b}`"))
            .collect();
        let deps_cell = if dep_list.is_empty() {
            "—".to_string()
        } else {
            dep_list.join(", ")
        };
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} | {} |",
            p.name, p.status, p.sort_order, deps_cell, p.title
        );
    }
    out
}

fn render_done(done: &[Plan]) -> String {
    let mut out = String::from("## Done\n\n");
    out.push_str("Completed plans. Their folders are gone. The merge commits hold the work.\n\n");
    out.push_str("| Plan | Merge commit | Result |\n|---|---|---|\n");
    for p in done {
        let commit = if p.merge_commit.is_empty() {
            "—"
        } else {
            &p.merge_commit
        };
        let _ = writeln!(out, "| `{}` | `{}` | {} |", p.name, commit, p.title);
    }
    out
}

/// Remove one `## heading` section (heading through next `## ` heading).
fn cut_section(doc: &str, heading: &str) -> String {
    let marker = format!("## {heading}");
    let lines: Vec<&str> = doc.lines().collect();
    let Some(start) = lines.iter().position(|l| l.trim() == marker) else {
        return doc.to_string();
    };
    let end = lines[start + 1..]
        .iter()
        .position(|l| l.starts_with("## "))
        .map(|i| start + 1 + i)
        .unwrap_or(lines.len());
    let mut out = lines[..start].join("\n");
    out.push('\n');
    out.push_str(&lines[end..].join("\n"));
    // Collapse any blank-line pileup left behind.
    while out.contains("\n\n\n") {
        out = out.replace("\n\n\n", "\n\n");
    }
    out
}

/// Pure core of [sync_plans_md] — testable without a filesystem.
/// Sections always land in canonical order: index, then done.
pub fn sync_doc(doc: &str, active: &[Plan], done: &[Plan], edges: &[(String, String)]) -> String {
    let base = cut_section(&cut_section(doc, "Plan index"), "Done");
    let mut out = base.trim_end().to_string();
    if !out.is_empty() {
        out.push_str("\n\n");
    }
    out.push_str(&render_index(active, edges));
    out.push('\n');
    out.push_str(&render_done(done));
    out.push('\n');
    out
}

/// Rewrite plans.md index/done sections from the DB.
pub fn sync_plans_md(project: &Project) -> anyhow::Result<()> {
    let conn = db::open(&project.db_path()?)?;
    let active: Vec<Plan> = db::list(&conn, None)?
        .into_iter()
        .filter(|p| p.status != "done")
        .collect();
    let done: Vec<Plan> = db::list(&conn, Some("done"))?;
    let edges = db::all_edges(&conn)?;

    let path = project.plans_md();
    let doc =
        std::fs::read_to_string(&path).unwrap_or_else(|_| "# Bebaiha — Plan System\n".to_string());
    crate::state::write_file(&path, &sync_doc(&doc, &active, &done, &edges))?;
    Ok(())
}

// ---------- plans.yaml ----------

fn yaml_quote(s: &str) -> String {
    let escaped = s
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n");
    format!("\"{escaped}\"")
}

pub fn render_yaml(active: &[Plan], deps: &[(String, String)]) -> String {
    let mut out = String::from(
        "# Plan registry. Generated by mind-mcp — edit via mind tools, not by hand.\n\
         # Source of truth: the per-project SQLite DB under ~/.local/share/mind-mcp/.\n\
         # Explainer: plans.md. Plan context: plans/<name>/.\n\nplans:\n",
    );
    for p in active {
        let _ = write!(
            out,
            "  - name: {}\n    title: {}\n    branch: {}\n    status: {}\n",
            p.name,
            yaml_quote(&p.title),
            yaml_quote(&p.branch),
            p.status
        );
        if p.progress.is_empty() {
            out.push_str("    progress: \"\"\n");
        } else {
            let _ = writeln!(out, "    progress: {}", yaml_quote(&p.progress));
        }
        let dep_list: Vec<String> = deps
            .iter()
            .filter(|(a, _)| a == &p.name)
            .map(|(_, b)| b.clone())
            .collect();
        if dep_list.is_empty() {
            out.push_str("    depends_on: []\n");
        } else {
            let _ = writeln!(out, "    depends_on: [{}]", dep_list.join(", "));
        }
        let _ = writeln!(out, "    order: {}\n", p.sort_order);
    }
    out
}

pub fn export_yaml(project: &Project) -> anyhow::Result<()> {
    let conn = db::open(&project.db_path()?)?;
    let active: Vec<Plan> = db::list(&conn, None)?
        .into_iter()
        .filter(|p| p.status != "done")
        .collect();
    let edges = db::all_edges(&conn)?;
    crate::state::write_file(&project.plans_yaml(), &render_yaml(&active, &edges))?;
    Ok(())
}

// ---------- brain.md ----------

#[derive(Clone, Debug)]
pub struct Lesson {
    pub id: i64,
    pub tag: String,
    pub text: String,
}

const BRAIN_HEADER: &str = "\
# Brain

Global lessons. One per line. Format: `- [tag] lesson <!--id:N-->`.
Short sentences. Active voice. Present tense.
Repo-specific findings belong in each repo's docs/FINDINGS.md, not here.

";

pub fn parse_brain(text: &str) -> Vec<Lesson> {
    text.lines()
        .filter_map(|line| {
            let rest = line.strip_prefix("- [")?;
            let (tag, after) = rest.split_once("]")?;
            let (text, id_part) = after.trim().split_once("<!--id:")?;
            let id: i64 = id_part.trim_end_matches("-->").trim().parse().ok()?;
            Some(Lesson {
                id,
                tag: tag.to_string(),
                text: text.trim().to_string(),
            })
        })
        .collect()
}

pub fn read_brain() -> anyhow::Result<Vec<Lesson>> {
    let path = crate::state::brain_path();
    match std::fs::read_to_string(&path) {
        Ok(text) => Ok(parse_brain(&text)),
        Err(_) => Ok(Vec::new()),
    }
}

fn brain_header_present(text: &str) -> bool {
    text.contains("Global lessons")
}

fn write_brain(lessons: &[Lesson]) -> anyhow::Result<()> {
    let mut out = String::new();
    let existing = std::fs::read_to_string(crate::state::brain_path())
        .map(|t| {
            if brain_header_present(&t) {
                t
            } else {
                BRAIN_HEADER.to_string()
            }
        })
        .unwrap_or_else(|_| BRAIN_HEADER.to_string());
    out.push_str(
        existing
            .lines()
            .take_while(|l| !l.starts_with("- ["))
            .collect::<Vec<_>>()
            .join("\n")
            .as_str(),
    );
    out.push('\n');
    for l in lessons {
        let _ = writeln!(out, "- [{}] {} <!--id:{}-->", l.tag, l.text, l.id);
    }
    crate::state::write_file(&crate::state::brain_path(), &out)
}

pub fn brain_add(tag: &str, text: &str) -> anyhow::Result<Lesson> {
    let mut lessons = read_brain()?;
    let next = lessons.iter().map(|l| l.id).max().unwrap_or(0) + 1;
    let lesson = Lesson {
        id: next,
        tag: tag.to_string(),
        text: text.to_string(),
    };
    lessons.push(lesson.clone());
    write_brain(&lessons)?;
    Ok(lesson)
}

pub fn brain_edit(id: i64, tag: Option<&str>, text: Option<&str>) -> anyhow::Result<Lesson> {
    let mut lessons = read_brain()?;
    let lesson = lessons
        .iter_mut()
        .find(|l| l.id == id)
        .context(format!("unknown lesson id {id}"))?;
    if let Some(t) = tag {
        lesson.tag = t.to_string();
    }
    if let Some(t) = text {
        lesson.text = t.to_string();
    }
    let updated = lesson.clone();
    write_brain(&lessons)?;
    Ok(updated)
}

pub fn brain_remove(id: i64) -> anyhow::Result<()> {
    let mut lessons = read_brain()?;
    let before = lessons.len();
    lessons.retain(|l| l.id != id);
    anyhow::ensure!(lessons.len() < before, "unknown lesson id {id}");
    write_brain(&lessons)
}
